### PR TITLE
Upgrade to Decidim 0.26

### PR DESCRIPTION
**Pull request by microstudi**
This PR upgrades the plugin for Decidim 0.26 or 0.27, working with webpacker.

Added/fixed:

- [x] Improve linting for javascript/css/erb/rb
- [x] Use npm packages for fullcalendar and gantt scripts
- [x] Add configuration options for colors and calendar view options
- [x] Add translations for calendar buttons (today, next, etc)
- [x] rake task to install npm packages
- [x] readme docs
- [x] Do not show unpublished, moderated or withdrawn events

### CODE REVIEW

**Comment by microstudi** [comment]
@paranoix I've made the upgrade for this plugin for Decidim 0.26. Tests should be passing if you authorize them.

**Comment by microstudi** [comment]
@paranoix @xdubx any change to review this PR? it fixes a lot of issues a part from upgrading.
Thanks!

**Comment by paranoix** [comment]
Good @microstudi  first of all thank you very much for your work and time dedicated to improve the module. We have had a period in which it has been difficult for us to maintain this due to workload. We have already made an update of the security bugs, update and dependencies of the Gems. We are reviewing the proposed code for the upgrade to version 0.26, we will test it in a virtual machine to see that everything is correct and functional and we will gladly accept the Merge. We will inform you as soon as it is ready. Best regards.

**Comment by microstudi** [comment]
thanks @paranoix, btw can you approve the workflows tests?

**Comment by luizsanches** [comment]
@microstudi I have an updated fork of the calendar. I talked to @andreslucena about the maintenance and he updated the page https://decidim.org/modules/. The project has already received some contributions :)

**Comment by microstudi** [comment]
Thanks for the info @luizsanches
May I ask why you didn't create a PR to this repo with your changes? 
If @andreslucena has updated the link on Decidim to your repo, does it mean that it is the official now?

**Comment by paarals** [comment]
hey @luizsanches 
I think we haven't met, I salute you!
in decidim, we have the problem with unofficial modules. an organization may have the authority but no longer work with it. it is a topic that was discussed in the decidim association (during the decidim fest). many of the companies in the ecosystem have started a discussion to have a github organization with the different modules with a shared authority. of course it will have some rules, you can participate in the debate here: https://github.com/decidim-ice/.github/discussions/2. with this initiative it is planned:
-keep the modules with the original name
-if the creator can't maintain it, there will be an ecosystem that will make it possible
- there will be a shared authority

to give you some context, we updated to 0.26 some time ago. the only thing that the authority is from alabs. from there, and from discussing it with the people of the association and other companies, we arrived at this discussion. we never decided to make a fork without knowing what future alabs envisions for this module and with the certainty of being aligned with the rest of the ecosystem in case it ever has to be done, do it jointly. the calendar module is one of those modules that many organizations use and, in our opinion, we should overcome past problems. as it seems "oficial calendar-module" is in your repo right now, it would be lovely if you can join in this ecosystem.

**Comment by andreslucena** [comment]
>  If @andreslucena has updated the link on Decidim to your repo, does it mean that it is the official now?

At least in the past, we've been changing the links to the maintained one. 

Mind that the rubygems gem is still owned by alabs: https://rubygems.org/gems/decidim-calendar

**Comment by microstudi** [comment]
> > If @andreslucena has updated the link on Decidim to your repo, does it mean that it is the official now?
> 
> At least in the past, we've been changing the links to the maintained one.
> 
> Mind that the rubygems gem is still owned by alabs: https://rubygems.org/gems/decidim-calendar

That's indeed a problem, on one side that's why we are trying to coordinate efforts so we don't do this double work (if I would see the PR with the upgrade from @luizsanches I've would use it). On the other side, in https://github.com/openpoke/decidim-module-calendar we have the upgrade and also other nice features (like configuring the colors).

**Comment by luizsanches** [comment]
@microstudi @paarals @andreslucena Good discussion. I will find out more about it. I vote to stay in the alabs repository. if this PR is approved, I may send a next one with the latest changes I made to my fork. OK?

**Comment by paranoix** [comment]
Good morning, @microstudi we have already performed the corresponding tests. We applied the update merge. Thanks for contributing to the development of the module. 

@luizsanches you can send the PR to perform the tests and apply it as well. Sorry guys, at the association we are under a heavy workload and we are having a hard time finding time to review some repos. About the discussion, having a shared authority is fine with us.

**Comment by andreslucena** [comment]
> That's indeed a problem, on one side that's why we are trying to coordinate efforts so we don't do this double work (if I would see the PR with the upgrade from @luizsanches I've would use it). 

Just so you know, the change to the fork was almost one year ago: https://github.com/decidim/decidim.org/commit/91a1154a6c6ab09d5cfee122974bc7bfb45dc7fe

> On the other side, in [openpoke/decidim-module-calendar](https://github.com/openpoke/decidim-module-calendar) we have the upgrade and also other nice features (like configuring the colors). 

That's the first time that I'm aware of that fork. I'd said that the main difference is that @luizsanches has reached out to hola [at] decidim [dot] org notifying the existence of its fork. We only can know what people communicate to us 😄 

As now there are 3 maintained forks, I think it's fear [to reflect that](https://github.com/decidim/decidim.org/commit/d2b4820cb15ad49b0d406ce6b9f650472441e1b9) in decidim.org. Feel free to open a PR changing descriptions and screenshots, although you should also update it in the README.

If you reach an agreement on a single "official" `decidim-calendar`, please tell us, so we can update the decidim.org website. Also you should publish it on rubygems and mention that in the other READMEs.

**Comment by microstudi** [comment]
@paranoix if you need help maintaining this plugin I can help, either publishing the gem in rubygems or reviewing contributions. Feel free to invite me if you want. 
Thanks for merging this!

**Pull request merged**
